// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACD4McNhiXv1MISE7jj6e8j_vYsBKROAs',
    appId: '1:778490720663:web:0bb8e8687f9b76542694d2',
    messagingSenderId: '778490720663',
    projectId: 'bmg2024-3f275',
    authDomain: 'bmg2024-3f275.firebaseapp.com',
    storageBucket: 'bmg2024-3f275.firebasestorage.app',
    measurementId: 'G-F7YSCVEZCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaMqcmXu2-imYqYuucNWZVpdbhYF6deSw',
    appId: '1:778490720663:android:3a60eb865aa9538f2694d2',
    messagingSenderId: '778490720663',
    projectId: 'bmg2024-3f275',
    storageBucket: 'bmg2024-3f275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkq7GU4T48bkyFQMLAL8pLP0wF4qZQsE',
    appId: '1:778490720663:ios:d805c8d64d992d062694d2',
    messagingSenderId: '778490720663',
    projectId: 'bmg2024-3f275',
    storageBucket: 'bmg2024-3f275.firebasestorage.app',
    iosBundleId: 'com.example.bmg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTkq7GU4T48bkyFQMLAL8pLP0wF4qZQsE',
    appId: '1:778490720663:ios:d805c8d64d992d062694d2',
    messagingSenderId: '778490720663',
    projectId: 'bmg2024-3f275',
    storageBucket: 'bmg2024-3f275.firebasestorage.app',
    iosBundleId: 'com.example.bmg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACD4McNhiXv1MISE7jj6e8j_vYsBKROAs',
    appId: '1:778490720663:web:c799bba2d15ca8472694d2',
    messagingSenderId: '778490720663',
    projectId: 'bmg2024-3f275',
    authDomain: 'bmg2024-3f275.firebaseapp.com',
    storageBucket: 'bmg2024-3f275.firebasestorage.app',
    measurementId: 'G-23G49W0Z6W',
  );
}
